### ISSUE TITLE
Финальный проект

### ISSUE THREAD

**Issue by marina-cyber** [onedanoken/timeseries_homeworks#12]
Вам надо или найти другой датасет или дополнить этот другими временными рядами (например, курсами других валют к доллару сша за рассматриваемый период времени).
Даже визуально видно, что все временные ряды в вашем датасете плохо различимы. Быстрая проверка t-критерием показала, что они действительно не отличаются. 

Ну и не надо так формально подходить к данным. Проверка  каждого по отдельности статистически неразличимых временных рядов на стационарность - это было  явно излишне.

**Comment by onedanoken** [comment]
Заменил датасет, теперь ряды различны.
Единственная проблема, которая еще осталась с прошлого варианта проекта - предсказания VARMA, хоть они сейчас лучше и стали, все равно метрики плохи, и тут я все же не могу понять в чём дело. В остальных моделях (VAR + нейросети) метрики хорошие.

**Comment by marina-cyber** [comment]
Уже лучше.

1. разложение на компоненты явно не соответствует временным рядам. Для каждого ряда будут разные окна. Ну и получать существенный тренд на стационарном ряде - ну такой себе результат.

2. Я не правильно поняла ваш код, или в нейронки вы запихивали немультивариативный ряд, а только одну ветку?

**Comment by onedanoken** [comment]
2. Да, на одной, но видимо тут надо обучение на всех столбцах сделать

**Comment by marina-cyber** [comment]
да

**Comment by marina-cyber** [comment]
проверьте, как вычисляете метрики. Остальное вполне нормально.

**Comment by onedanoken** [comment]
Сделал, метрики проверил, всё ок (сверил с лекцией формулу SMAPE), посмотрите пожалуйста @marina-cyber

**Comment by marina-cyber** [comment]
Зачтено.
